# Generated by Django 5.2 on 2025-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casedetails',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(blank=True, max_length=255, null=True)),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('responsible_dept', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('appeal_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'casedetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Claimdetails',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'claimdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemdetails',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('auction_notice_url', models.CharField(blank=True, max_length=255, null=True)),
                ('item_spec_url', models.CharField(blank=True, max_length=255, null=True)),
                ('item_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('valuation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('item_note', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, max_length=255, null=True)),
                ('court_date', models.DateTimeField(blank=True, null=True)),
                ('auction_failures', models.IntegerField(blank=True, default=0, null=True)),
                ('item_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'itemdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listingdetails',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('list_type', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'listingdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partydetails',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_type', models.CharField(blank=True, max_length=255, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'partydetails',
                'managed': False,
            },
        ),
    ]
